<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-10-02 20:44
=======
# Generated by Django 4.2.5 on 2023-09-19 22:37
>>>>>>> 153056333833bb1116f05d89ed007de5168d6262

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_category', models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=100)),
<<<<<<< HEAD
                ('variation_value', models.CharField(max_length=100)),
=======
>>>>>>> 153056333833bb1116f05d89ed007de5168d6262
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
